kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gceme-backend-staging
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: gceme
        role: backend
        env: staging
    spec:
      containers:
      - name: backend
        image: docker.io/dockergm/private-lab:staging.99
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080
