kind: Service
apiVersion: v1
metadata:
  name: gceme-frontend
spec:
  type: LoadBalancer
  externalIPs: [172.16.78.201]
  ports:
  - name: http
    port: 8082
    targetPort: 80
    protocol: TCP
  selector:
    app: gceme
    role: frontend
