kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gceme-frontend-staging
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: gceme
        role: frontend
        env: staging
    spec:
      containers:
      - name: frontend
        image: docker.io/dockergm/private-lab:staging.99
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "app -frontend=true -backend-service=http://gceme-backend:8080 -port=80"]
        ports:
        - name: frontend
          containerPort: 80
